# Creation of ndarray using array()

creation of 1D array using aarray() from list or tuple

In [2]:
#list
l=[23,43,53,63,73]
print(l)
print(type(l))

[23, 43, 53, 63, 73]
<class 'list'>


In [10]:
import numpy as np
l=[23,43,53,63,73]
print('list is:',l)
print(type(l))

arr=np.array(l)  # converting list to 1D array
print('array is:',arr)
print(type(arr))

list is: [23, 43, 53, 63, 73]
<class 'list'>
array is: [23 43 53 63 73]
<class 'numpy.ndarray'>


In [12]:
# creation of 1D array from tuple
t=(2,34,5,6,9)
print(type(t))

arr=np.array(t) # convert tuple to 1D array
print(arr)
print(type(arr))

<class 'tuple'>
[ 2 34  5  6  9]
<class 'numpy.ndarray'>


# Checking different properties  of ndarray

In [23]:
# check dimension 
l=[23,43,53,63,73]
pr=np.array(l)  # converting list to 1D array
print('array is:',pr)
print('dimension is:',pr.ndim)

array is: [23 43 53 63 73]
dimension is: 1


In [21]:
# checking shpae 
l=[3,4,5,6,7,8,89,37]
ar=np.array(l)
print('shape is:',ar.shape)

shape is: (8,)


In [24]:
# checking size
# size means the number of elements
print('size is:',pr.size)

size is: 5


In [25]:
# checking data type
print('data type is:',pr.dtype)

data type is: int32


creation of 2D array from nested list using array()

In [26]:
l1=[[10,20,30],[40,50,60],[70,80,90]]
tr=np.array(l1)
print(tr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [30]:
# checking different properties 
print(tr.ndim)
print(tr.shape)
print(tr.size)
print(tr.dtype)

2
(3, 3)
9
int32


creation of 3D array from nested matrix using array()

In [43]:
l=[[[1,2,3],[4,5,6],[7,8,9]],[[2,2,2],[3,3,3],[5,5,5]]]

print(l)
print(type(l))

gr=np.array(l)

print(gr)


# cheching different properties of 3D array
print(gr.ndim)
print(gr.shape)
print(gr.size)
print(gr.dtype)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[2, 2, 2], [3, 3, 3], [5, 5, 5]]]
<class 'list'>
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 2 2]
  [3 3 3]
  [5 5 5]]]
3
(2, 3, 3)
18
int32


In [45]:
# upcasting
l=[122,33,44,5.58,6.6]
arrr=np.array(l) # upcasting
print(arrr)

[122.    33.    44.     5.58   6.6 ]
