# Creation of ndarray by using specific datatypes

In [5]:
import numpy as ny

### A- Creation of ndarray using int,float,bool,complex,str datatype


In [14]:
#01- Creation of ndarray using int type
l=[2,3,4,5,8.8,9.7]
nrr=ny.array(l,dtype='int64')
print(nrr)

# properties
print('dimension is',nrr.ndim)
print('shape is::',nrr.shape)
print('size is::',nrr.size)
print('data type is::',nrr.dtype)

[2 3 4 5 8 9]
dimension is 1
shape is:: (6,)
size is:: 6
data type is:: int64


In [12]:
# another way
nrr=ny.array([12,34,5.6,7.4,4.33],dtype=ny.int)
print(nrr)


# properties
print('dimension is',nrr.ndim)
print('shape is::',nrr.shape)
print('size is::',nrr.size)
print('data type is::',nrr.dtype)

[12 34  5  7  4]
dimension is 1
shape is:: (5,)
size is:: 5
data type is:: int32


C:\Users\ASUS\AppData\Local\Temp\ipykernel_12880\411624664.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  nrr=ny.array([12,34,5.6,7.4,4.33],dtype=ny.int)


In [17]:
#02- Creation of ndarray using float type
l1=[5.44,7.44,2,5,9.006]
nrr=ny.array(l1,dtype="float32")
print(nrr)

# properties
print('dimension is',nrr.ndim)
print('shape is::',nrr.shape)
print('size is::',nrr.size)
print('data type is::',nrr.dtype)

[5.44  7.44  2.    5.    9.006]
dimension is 1
shape is:: (5,)
size is:: 5
data type is:: float32


In [19]:
#03- Creation of ndarray using bool type
l2=[5.44,6,7.6,True,False,0,1,'priti']
nrr=ny.array(l2,dtype="bool")
print(nrr)

# non-zero value means true 
# properties
print('dimension is',nrr.ndim)
print('shape is::',nrr.shape)
print('size is::',nrr.size)
print('data type is::',nrr.dtype)

[ True  True  True  True False False  True  True]
dimension is 1
shape is:: (8,)
size is:: 8
data type is:: bool


In [24]:
#04- Creation of ndarray using complex type
l3=[9,5,43,13.2,2+3j,True,False]
nrr=ny.array(l3,dtype="complex")
print(nrr)

[ 9. +0.j  5. +0.j 43. +0.j 13.2+0.j  2. +3.j  1. +0.j  0. +0.j]


In [28]:
#05- Creation of ndarray using str type
l=['smruti',12,4.45,77,8.78,'Jyoti',False,10+2j]
nrr=ny.array(l,dtype='str')
print(nrr)

['smruti' '12' '4.45' '77' '8.78' 'Jyoti' 'False' '(10+2j)']


### B- Creation of ndarray using object type

In [30]:
# Heterogeneous -- we can store different data types here
l=['smruti','raja',123,888,987,2+3j,True,False,0,1]
nrr=ny.array(l,dtype='object')
print(nrr)
print(nrr.dtype)

['smruti' 'raja' 123 888 987 (2+3j) True False 0 1]
object
