In [ ]:
# Dt- 15-09-2022

# Creation of ndarray using zeros() ones() and full() 

In [34]:
#1) creation of ndarray using zeros():-
#2) creation of ndarray using ones():-
#3) creation of ndarray using full():-

#### 1) creation of ndarray using zeros():-

In [21]:
# Create 1D array with size 10 and dill 0
ar=np.zeros(10)
print(ar)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [25]:
# Create 2*3 array and fill zero
ar=np.zeros((2,3)) # inside tuple provide this val
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# Create 4*4 array and fill with zeros with int value
ar=np.zeros((4,4),dtype='int')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
# craete a 3D array with shape 2*3*3
# 2 - no. of 2D array
# 3- no. of rows in 2D array
# 3- no. of coloumns in 2D array
arrr=np.zeros((2,3,3))
arrr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# create 4D array with shape 2*2*3*3

arrr=np.zeros((2,2,3,3))
arrr

# 2- no. of 3D array
# 2- no. of 2D array
# 3-no. of rows
# 3- no. of columns

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

### 2) creation of ndarray using ones():

In [35]:
 #shape : int or sequence of ints
  #      Shape of the new array, e.g., ``(2, 3)`` or ``2``.
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
arr=np.ones(10,dtype='int')
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
#2D
arr=np.ones((2,3),dtype='int')
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
#3D
arr=np.ones((2,3,3),dtype='int')
arr

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [40]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

### 3) creation of ndarray using full():-

In [41]:
prr=np.full(10,999)
prr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [43]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas

In [44]:
# create 2D array and fill 888
prr=np.full((2,3),666)
prr

array([[666, 666, 666],
       [666, 666, 666]])

In [49]:
# create 3D array and fill 888
prr=np.full((2,3,3),666,dtype='bool')
prr

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [48]:
# create 4D array and fill 888
prr=np.full((2,2,3,3),666,dtype='complex')
prr

array([[[[666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j]],

        [[666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j]]],


       [[[666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j]],

        [[666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j],
         [666.+0.j, 666.+0.j, 666.+0.j]]]])

# Thank u