# Creation of ndarray using eye() and identity()

1) what identity matrix?
    ans::matrix diagonal filled with 1 and  others are filled with 0

In [28]:
import numpy as np

In [5]:
help(np.eye)


Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

#Help on function eye in module numpy:

#eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
   Return a 2-D array with ones on the diagonal and zeros elsewhere.

 N-rows(mandatory)
 M-cols(not mandatory)
 K- diagonal

In [6]:
# craete 3*3 identity matrix using eye() functios
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# if we not pass anything for M then M value will be same as N
  # means here N=3,M=3
arr=np.eye(3,dtype='int')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
# Creation of 3*4 matrix using eye() 
  # here N=3,M=4
arr=np.eye(3,4,dtype='int')
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [23]:
# Creation of 4*4 matrix using eye() 
  # here N=4,M=4
    
    # k represent diagonal
    # in main diagonal k=0 , main diagonal upper diagonal is 1 then 2 then 3
    # in main diagonal k=0 ,main diagonal lower diagonal is -1,-2,-3
arr=np.eye(3,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [29]:
# customization of diagonal
ar=np.eye(4,4,k=1,dtype='int')
ar

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [33]:
# customization of diagonal
ar=np.eye(4,4,k=2,dtype='int')
ar

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
# customization of diagonal
ar=np.eye(4,4,k=3,dtype='int')
ar

array([[0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
# customization of diagonal
ar=np.eye(4,4,k=-1,dtype='int')
ar

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [36]:
# customization of diagonal
ar=np.eye(4,4,k=-2,dtype='int')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [37]:
# customization of diagonal
ar=np.eye(4,4,k=-3,dtype='int')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0]])

In [38]:
# customization of diagonal
ar=np.eye(4,4,k=10,dtype='int')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
# customization of diagonal
ar=np.eye(4,4,k=-10,dtype='int')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
# customization of diagonal
 # 
ar=np.eye()
ar
# here u get an error bcz u r not passing anything

TypeError: eye() missing 1 required positional argument: 'N'

In [29]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.

In [ ]:
#identity(n, dtype=None, *, like=None)
 #   Return the identity array.
#    n= here n represent both number of rows and coloumns

# square matrix=no. of rows and columns are same

In [31]:
ar=np.identity(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
ar=np.identity(4,dtype='int')
ar

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [36]:
ar=np.identity(3,3,dtype='int')
ar
# here u get an error

TypeError: identity() got multiple values for argument 'dtype'