# Creation of ndarray() using empty() and diag() functions 

In [38]:
import numpy as np

In [65]:
# empty() - It will give system generated value (garbage value)-- it give good performance
ar=np.empty((2,2))
ar

array([[9.99359619e-312, 4.67296746e-307],
       [1.69121096e-306, 1.89145198e-307]])

In [70]:
#zeros() 
#in the case zeros it will give 0 
arr=np.zeros((2,2))
arr



array([[0., 0.],
       [0., 0.]])

In [69]:

# ones()
 # in the case of ones it will give 1
arr=np.ones((2,2))
arr


array([[1., 1.],
       [1., 1.]])

In [ ]:
# diag()- it means diagonal
# if we are passing 2D array it will return the diagonal but if we will pass 1D array then it will construct 2D array and make 1D array as a main diagonal
 # sometimes it is used to create a array or sometimes it is used to return the diagonal elemnt

In [78]:
# passing 2D array in diag()
prr=np.arange(16).reshape(4,4)
prr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
# here we get the main diagonal
np.diag(prr)

array([ 0,  5, 10, 15])

In [86]:
np.diag(prr,k=1)

array([ 1,  6, 11])

In [87]:
np.diag(prr,k=-3)

array([12])

In [88]:
np.diag(prr,k=-2)

array([ 8, 13])

In [89]:
np.diag(prr,k=2)

array([2, 7])

In [90]:
np.diag(prr,k=3)

array([3])

In [91]:
np.diag(prr,k=-1)

array([ 4,  9, 14])

In [95]:
# passing 1D array in diag functions
   # It will create 2D array
priti=np.arange(5)
priti

array([0, 1, 2, 3, 4])

In [96]:
# It make this array([0, 1, 2, 3, 4]) values as main diagonal and then construct a 2D array using 0 in other diagonal
np.diag(priti)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [98]:
np.diag(priti,k=-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0]])

In [100]:
np.diag(priti,k=-2)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0]])

In [101]:
np.diag(priti,k=3)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [102]:
np.diag(priti,k=-3)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0]])

In [103]:
# diagonal 2 is [0, 1, 2, 3, 4]
np.diag(priti,k=2)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [104]:
ss=np.arange(3,9)
ss

array([3, 4, 5, 6, 7, 8])

In [105]:
np.diag(ss)

array([[3, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 8]])

In [106]:
np.diag(ss,k=2)

array([[0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [107]:
np.diag(ss,k=-3)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 8, 0, 0, 0]])

In [108]:
np.diag(ss,k=2)

array([[0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [109]:
np.diag(ss,k=-2)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 8, 0, 0]])

In [110]:
np.diag(ss,k=3)

array([[0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])