#Creation of ndarray using rand(),unifrom()

In [ ]:
import numpy as np



In [37]:
arr=np.random.rand()
print(arr)

0.7617609146010658


In [38]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [39]:
arr=np.random.rand(2,2)
print(arr)

[[0.116149   0.61352105]
 [0.39288315 0.44855597]]


In [40]:
arr=np.random.rand(3,2,2)
print(arr)

[[[0.12813187 0.31349118]
  [0.39456459 0.51337222]]

 [[0.05718064 0.75047048]
  [0.18574777 0.73218576]]

 [[0.56807104 0.77628763]
  [0.98907657 0.68405542]]]


In [22]:
arr=np.random.rand(10000,10000)
print(arr)

[[0.4756977  0.02639478 0.81665382 ... 0.50507135 0.62238048 0.91355219]
 [0.69856722 0.33110377 0.40946864 ... 0.91826866 0.66858461 0.97866258]
 [0.04190732 0.71932428 0.95472693 ... 0.19944097 0.60313436 0.75991486]
 ...
 [0.32349108 0.94308664 0.92694935 ... 0.33345452 0.79477021 0.67755971]
 [0.49656111 0.61897973 0.86546689 ... 0.35969836 0.23260527 0.27862424]
 [0.89912281 0.50915179 0.33596964 ... 0.35585742 0.64866408 0.32805275]]


In [ ]:
arr=np.random.rand(10000,10000)
import matplotlib.pyplot as plt
plt.hist(arr)
plt.show()

In [ ]:
arr=np.random.rand(3,4)
import matplotlib.pyplot as plt
plt.hist(arr)
plt.show()

In [ ]:
# 