#Creation of ndarray using rand(),unifrom()

In [36]:
import numpy as np

In [37]:
arr=np.random.rand()
print(arr)

0.7617609146010658


In [38]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [39]:
arr=np.random.rand(2,2)
print(arr)

[[0.116149   0.61352105]
 [0.39288315 0.44855597]]


In [40]:
arr=np.random.rand(3,2,2)
print(arr)

[[[0.12813187 0.31349118]
  [0.39456459 0.51337222]]

 [[0.05718064 0.75047048]
  [0.18574777 0.73218576]]

 [[0.56807104 0.77628763]
  [0.98907657 0.68405542]]]


In [41]:
arr=np.random.rand(100,100.)
print(arr)

[0.8362051  0.27213458 0.15401298 ... 0.12859153 0.40403371 0.91684542]
