In [2]:
# creation of ndarray using logspace()
import numpy as np

In [4]:
# linspace()---linear
# example-1
 # 1 to 10 number both are included with 5 element and the gap between each number is same.
arr=np.linspace(1,10,num=5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [27]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [5]:
# exampel-2
arr=np.linspace(1,10,num=4)
print(arr)

[ 1.  4.  7. 10.]


In [ ]:
# example-3
 # if we not pass num value then by default it will give u 50 value and gap b/w each value is same
arr=np.linspace(1,10,num=4)
print(arr)

In [ ]:
# linear : 2 4 6 8 10 (gap is same)
# logarithm : 2 4 8 16 32 (gap is increasing)
#            : 10 100 1000 10000 100000

In [8]:
# logspace()
# example-1
arr=np.logspace(1,2,num=4)
print(arr)

[ 10.          21.5443469   46.41588834 100.        ]


In [29]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [9]:
# example=2
arr=np.logspace(1,10,num=4)
print(arr)

[1.e+01 1.e+04 1.e+07 1.e+10]


In [ ]:
# example-3
arr=np.logspace(1,10,num=4)
print(arr)

In [10]:
# example-4
arr=np.logspace(1,2,num=5)
print(arr)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [16]:
# example-5
arr=np.logspace(1,3,num=5)
print(arr)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [17]:
# example-6
# If we not pass the num value then it will give 50 value by default.
arr=np.logspace(1,10,dtype=int)
print(arr)

[         10          15          23          35          54          82
         126         193         294         449         686        1048
        1599        2442        3727        5689        8685       13257
       20235       30888       47148       71968      109854      167683
      255954      390693      596362      910298     1389495     2120950
     3237457     4941713     7543120    11513953    17575106    26826957
    40949150    62505519    95409547   145634847   222299648   339322177
   517947467   790604321  1206792640  1842069969 -2147483648 -2147483648
 -2147483648 -2147483648]


In [13]:
# example-7
arr=np.logspace(2,3,num=5)
print(arr)

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]


In [14]:
# example-8
arr=np.logspace(2,3,num=5,dtype=int)
print(arr)

[ 100  177  316  562 1000]


In [18]:
# example-9 
# also we can change the base
arr=np.logspace(2,3,num=5,base=2,dtype=int)
print(arr)

[4 4 5 6 8]


In [31]:
# example-10
arr=np.logspace(2,5,num=5,base=2,dtype=int)
print(arr)

[ 4  6 11 19 32]


In [32]:
# example-11
#endpoint=False ---> It will exclude the last value. 
 # in example-10 we get 32 but here we not get 32 bcz endpoint=False it excluded the last value.
arr=np.logspace(2,5,num=5,base=2,dtype=int,endpoint=False)
print(arr)

[ 4  6  9 13 21]
