# creation of  ndarray using zeros_like() ones_like() empty_like() full_like()

In [10]:
import numpy as np

### (1) zeros_like()


In [11]:
# zeros
arr=np.zeros((2,2,))
print(arr)

[[0. 0.]
 [0. 0.]]


In [12]:

arr=np.zeros((2,2,),dtype=int)
print(arr)

[[0 0]
 [0 0]]


In [32]:
# normal array
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
# zeros_like()
  # here we are giving the array a
arr=np.zeros_like(a)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


### (2) ones_like()

In [14]:

arr=np.ones((2,2,))
print(arr)

[[1. 1.]
 [1. 1.]]


In [15]:

arr=np.ones((2,2,),dtype=int)
print(arr)

[[1 1]
 [1 1]]


In [35]:
# ones_like()
  # here we are giving the array a
arr=np.ones_like(a)
print(arr)

[1 1 1 1 1 1 1 1 1 1]


### (3) empty_like()

In [53]:
# empty will give random value(default value / garbage value)
arr=np.empty((2,2),dtype=int)
print(arr)

[[666 666]
 [666 666]]


In [74]:
# empty_like()
arr=np.empty_like((a))
print(arr)

[0 0 0 0 0 0 0 0 0 0]


### (4)full_like()

In [83]:
#full 
arr=np.full((2,2),666)
print(arr)

[[666 666]
 [666 666]]


In [82]:
#full_like 
arr=np.full_like((a),322)
print(arr)

[322 322 322 322 322 322 322 322 322 322]
