### ndarray attributes

In [5]:
import numpy as np

In [ ]:
# ndim
#shape
#size
#itemsize
#dtype

### (1) ndim

In [4]:
# ndim= dimension of the array
arr=np.arange(10)
print(arr)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [9]:
arr=np.arange(20).reshape(5,4)
print(arr)
print(arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
2


In [10]:
arr=np.arange(27).reshape(3,3,3)
print(arr)
print(arr.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
3


### (2) shape

In [15]:
arr1=np.arange(20)
print(arr1)
print(arr1.shape)
# It will give the output in the form of tuple.
print(type(arr1.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
<class 'tuple'>


In [17]:
arr2=np.arange(27).reshape(3,3,3)
print(arr2)
print(arr2.shape)
print(type(arr2.shape))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(3, 3, 3)
<class 'tuple'>


### (3)size

In [18]:
arr4=np.arange(10)
print(arr4)
print(arr4.size)

[0 1 2 3 4 5 6 7 8 9]
10


In [21]:
arr2=np.arange(27).reshape(3,3,3)
print(arr2)
print(arr2.size)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
27


### (4)itemsize & dtype 

In [27]:

# individual element is called item
# individual element taking how many bytes i.e itemsize
arr5=np.arange(5)
print(arr5)
print(arr5.itemsize)
print(arr5.dtype)

[0 1 2 3 4]
4
int32


In [28]:
arr5=np.arange(5)
print(arr5)
print((arr5.itemsize)*len(arr5))

[0 1 2 3 4]
20


### changing dtype

In [30]:
# changing dtype
arr5=np.arange(5,dtype='int8')
print(arr5)
print(arr5.itemsize)
print(arr5.dtype)
print((arr5.itemsize)*len(arr5))

[0 1 2 3 4]
1
int8
5
